[package]
name = "hammer-online"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.5.4"

